### ISSUE TITLE
Add support for company API

### ISSUE THREAD

**Issue by jeremyhaile** [fullcontact/fullcontact-api-ruby#34]
The company API has officially been released. It'd be nice if the gem supported it.

https://www.fullcontact.com/developer/docs/company/

**Comment by Xorlev** [comment]
I'll be rolling a new gem version tomorrow with Company API support @jeremyhaile. I'll update this when that's released.

**Comment by jeremyhaile** [comment]
@Xorlev thanks!

**Comment by Xorlev** [comment]
0.10.0 is released with Company API support. If you run into any issues, please open an issue and we'll address it as soon as possible.
