### ISSUE TITLE
Just a simple hash?

### ISSUE THREAD

**Issue by wetzler** [fullcontact/fullcontact-api-ruby#35]
Is there a way to get the results of a request back as a simple hash rather than the Hashie format? Or, perhaps you could provide a couple of examples of how to interact with the Hashie object?

(I'm not familiar with Hashie so having to learn it is creating a barrier for my script creation; a simple JSON response would be much more straightforward for me :))

**Comment by wetzler** [comment]
Solved my own issue :)
You can convert back to a regular hash like this for ease of parsing:

person = FullContact.person(email: example_email, style: "dictionary").to_hash

**Comment by Xorlev** [comment]
> I'm not familiar with Hashie so having to learn it is creating a barrier for my script creation

I think this is likely the case for many developers, I'll add it to the readme examples. Thanks for opening the issue!
