### ISSUE TITLE
response formatting

### ISSUE THREAD

**Issue by gabeodess** [fullcontact/fullcontact-api-ruby#36]
We would like to be able to retrieve the data with the default FullContact formatting.  It looks like the gem is reformatting all the keys to be underscored, but our app is expecting camelCasing.  Is it possible to get a response with camelCasing instead?

**Comment by Xorlev** [comment]
That's not something the gem supports right now, but I'd be open to making it configurable. Perhaps something along the lines of:

```ruby
FullContact.configure do |config|
  config.api_key = 'fullcontact_api_key_goes_here'
  config.keyformat = :camelcase # :snakecase default
end
```

**Comment by gabeodess** [comment]
Yeah, that would be great.  What are you doing in the gem to switch it from camelcase to snakecase?  Doesn't FullContact hand you camelcased JSON?

**Comment by Xorlev** [comment]
We introduced a filter into our faraday to make our responses more idiomatic Ruby structures. We use [plissken](https://github.com/futurechimp/plissken) to do the [transformation](https://github.com/fullcontact/fullcontact-api-ruby/blob/d026547305595a497d664cda7bd0847b7e2c26de/lib/faraday/response/rubyize.rb) now.

**Comment by gabeodess** [comment]
Looks like you could add a simple boolean option and check it in connection.rb.

```ruby
builder.use Faraday::Response::Rubyize unless raw or skip_snakify
```

Thoughts?

**Comment by Xorlev** [comment]
Yep, that's about the simplest thing that'd work. I'm working on a patch now.

**Comment by gabeodess** [comment]
Great, thanks!

**Comment by Xorlev** [comment]
I just cut 0.11.0 with that change (`skip_rubyize`). Let me know how it works for you.

**Comment by gabeodess** [comment]
Works like a charm :)

Thanks!
