### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by gabeodess** [fullcontact/fullcontact-api-ruby#37]
Hello,

We are running into rate limits issues, but are not sure how to retrieve the X-Rate-Limit-Remaining header from the response.  It would be nice if there was a key "headers" or something in the Hashie::Mash that contained all the response headers for review.

**Comment by Xorlev** [comment]
Hi Gabe,

Apologies for the late reply -- I agree, that information should be available. My only concern is that changing the format might be backwards-incompatible with certain users.

Alternatively, what if the gem handled ratelimiting for you with a few configurable schemes? 1) sleeps until rate would be available 2) throws an exception with metadata so you can do it yourself.

**Comment by gabeodess** [comment]
I like the idea of it throwing an exception at a certain threshold, then we could catch the error and handle it appropriately.  It still would be nice to have access to the headers though, as there might be other headers that could perform different functions, or if new headers are added down the road.

What if it was a configuration option like ```config.include_headers_in_response = true``` type of thing?  Or add more flexibility with ```config.response_headers_key = "headers"``` where if they don't set the headers key then it doesn't include the headers.

I'm much more a fan of giving users the data and letting them decide how to deal with it instead of trying to guess how most users would want to deal with it.  Keeps the gem light and flexible.

**Comment by Xorlev** [comment]
I'll push automatic handling of limits back for now. 

`config.include_headers_in_response = true` seems adequate to me, I can't see much of a case for allowing configurability of the headers key offhand. In a few versions (TBD), `config.include_headers_in_response = true` will be the default and the configuration parameter will be removed.

**Comment by gabeodess** [comment]
Sounds great, thanks!

**Comment by Xorlev** [comment]
`http_headers` is now a key in the response (as well as an accessor on the exceptions) when `include_headers_in_response` is enabled. v0.12.0
