### ISSUE TITLE
FullContact.company(domain: 'fullcontact.com') returns no method error

### ISSUE THREAD

**Issue by jonathandenney** [fullcontact/fullcontact-api-ruby#38]
With FullContact initialized, when I make calls to the person API it works perfectly. However each call I make to the company API returns a no method error. There seems to be an issue with the ruby wrapper's company API functionality.

![screen shot 2015-07-06 at 8 59 19 pm](https://cloud.githubusercontent.com/assets/5561731/8536635/e902e048-2421-11e5-9d5b-5ce01636f72a.png)

**Comment by Xorlev** [comment]
Hi Jonathan,

Company API functionality was introduced in 0.10.0 of the gem (newest is
0.11.0). You appear to be using 0.9.0. If you upgrade it should start
working.

*Michael Rose*
Senior Software Engineer, Data Science
*Full*Contact | fullcontact.com
<https://www.fullcontact.com/?utm_source=FullContact%20-%20Email%20Signatures&utm_medium=email&utm_content=Signature%20Link&utm_campaign=FullContact%20-%20Email%20Signatures>
m: +1.720.837.1357 | t: @xorlev


All Your Contacts, Updated and In One Place.
Try FullContact for Free
<https://www.fullcontact.com/?utm_source=FullContact%20-%20Email%20Signatures&utm_medium=email&utm_content=Signature%20Link&utm_campaign=FullContact%20-%20Email%20Signatures>

**Comment by jonathandenney** [comment]
Awesome that did it. Thanks!
